### ISSUE TITLE
How to preserve image style?

### ISSUE THREAD

**Issue by raimkulovr** [VisualSystemsCorp/vsc_quill_delta_to_html#29]
This is printed delta to Json representation and html conversion result:
![image](https://github.com/user-attachments/assets/7cbecae3-8978-455c-8ac2-45f0afd18478)

**Comment by dsyrstad** [comment]
@raimkulovr I think the problem is that you have a `style` attribute with a string of `"width: ...; height: ...;"`. According to this: https://quilljs.com/docs/guides/designing-the-delta-format#embedded-content, only a direct `width` attribute is supported (there is no `style` attribute since that is CSS, not Quill Delta), so your delta should look like something like:

```json5
[
//...
          {
            "insert": {"image": "http://yahoo.com/abc.jpg"},
            "attributes": {"width": 100}
          },
 //...
]
```

Where `width` is a direct attribute, and there is no `style` attribute.

I've updated the image tests to test this, and it seems to work:

```dart
      test('should render image and image links', () {
        final ops = [
          {
            'insert': {'image': 'http://yahoo.com/abc.jpg'}
          },
          {
            'insert': {'image': 'http://yahoo.com/def.jpg'},
            'attributes': {'link': 'http://aha'},
          },
          {
            'insert': {'image': 'http://yahoo.com/abc.jpg'},
            'attributes': {'width': 100},
          },
        ];
        final qdc = QuillDeltaToHtmlConverter(ops);
        final html = qdc.convert();
        expect(
            html,
            '<p>'
            '<img class="ql-image" src="http://yahoo.com/abc.jpg"/>'
            '<a href="http://aha" target="_blank">'
            '<img class="ql-image" src="http://yahoo.com/def.jpg"/>'
            '</a>'
            '<img class="ql-image" width="100" src="http://yahoo.com/abc.jpg"/>'
            '</p>');
      });
```

**Comment by raimkulovr** [comment]
Got it, thank you! I'm adding images via flutter_quill_extensions, so it's unfortunate to learn that they are using an improper format.
