### ISSUE TITLE
isValidHexColor expects color without alpha

### ISSUE THREAD

**Issue by ndcube** [VisualSystemsCorp/vsc_quill_delta_to_html#3]
In OpAttributeSanitizer's `sanitize` function it calls `isValidHexColor` to determine if the color attribute is valid and it expects the color to be in the form of e.g `#5E35B1`, but the color at that point is actually `#FF5E35B1` containing the alpha channel as well. Same is true for `isValidRGBColor`. The regexp in both these functions only accepts colors without an alpha channel.

I used the default toolbar from the quill editor (`QuillToolbar.basic`) and set colors using the default color and background color buttons. These set color attributes in the document delta like:
`insert⟨ hello ⟩ + {color: #FF5E35B1}`

The alpha should probably be stripped from the color during conversion or accepted by these validator functions. E.g if I make `isValidHexColor` to accept it as it is the resulting html with this `argb` color is displayed properly using the `flutter_html` package, although I think it is not proper html becuase html uses `rgb` or `rgba`.

`<p><span style="color:#FF5E35B1">hello</span></p`

Tested on both _macos_ and _web_ with
- vsc_quill_delta_to_html 1.0.3
- flutter_quill 7.2.1

**Comment by dsyrstad** [comment]
You are correct, HTML/CSS only takes rgb or rgba (https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color and https://drafts.csswg.org/css-color/#hex-notation). 

However, the Quill format isn't HTML per se and it doesn't say what it should be other than a "hex" color (https://quilljs.com/docs/delta/#document). It only gives examples of rgb hex colors, although they look like CSS hex colors with the `#` prefix. However this Quill link of the delta design (https://github.com/quilljs/quill/blob/27d9a6eab5dc98e7ad7b0bb3d4b736b4e1c0c87b/website/content/guides/designing-the-delta-format.mdx?plain=1#L82) says it only uses six digit colors (but the other link shows 3 or 6 digits). This [code](https://github.com/quilljs/quill/blob/27d9a6eab5dc98e7ad7b0bb3d4b736b4e1c0c87b/formats/color.ts#L4) shows that it also handles `rgb(r,g,b)` and turns it into a `#<hex>` color string. Otherwise, parchment can take whatever string you give it for color, including names like `red`.  In any case, there's no mention of support for the alpha channel.

It seems that `flutter_quill` broke the color picker for the basic toolbar starting after version 7.1.18. At this version, it inserted 6 digit hex colors. Now the color picker dialog has changed in 7.2.1 and it is always 8 digits and include the alpha value as the first two digits - as you observed. Based on what I see in the Quill doc/code, hex colors should always be 3 or 6 digits.

My position is that `flutter_quill` is that version 7.2.x introduced a bug with colors.

Aside, if `flutter_html` is properly accepting argb colors, rather than rgba, I'd say that's wrong based on the CSS spec.

**Comment by ndcube** [comment]
Thanks for the response, I have created an issue for that in `flutter_quill` https://github.com/singerdmx/flutter-quill/issues/1257

**Comment by dsyrstad** [comment]
@Alspb You can handle your own color format by implementing an inline style handler. See https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html#rendering-inline-styles. You could handle `#AARRGGBB` colors using this.

**Comment by dsyrstad** [comment]
@Alspb You can handle your own color format by implementing an inline style handler. See https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html#rendering-inline-styles. You could handle `#AARRGGBB` colors using this.

**Comment by dsyrstad** [comment]
@Alspb In order to use InlineStyles with colors right now, you'd have to have your own attribute name - like `custom_color`. The `color` attribute is sanitized right now in a hard-coded fashion. A possible enhancement would be to https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html/blob/e976e69f30b44fa1a4ddc8f2f5f8e77501441469/lib/src/op_attribute_sanitizer.dart#L201 and allow a custom sanitizer for colors.

**Comment by dsyrstad** [comment]
> Could this custom sanitizer for colors be implemented without modifying the source code?

@Alspb No, you would need to enhance `OpAttributeSanitizerOptions` to have a flag to support hex colors with alpha and then change the sanitizers to look at this flag.

**Comment by dsyrstad** [comment]
Addressed with PR #16
